import type { ProjectOverview } from '@spravio/types'

export function buildReportHtml(overview: ProjectOverview): string {
  const { project, currentSprint, progressByStatus, developers } = overview
  const sprint = currentSprint?.sprint

  const statusRows = [
    { label: 'Done', count: progressByStatus.done, color: '#16A34A' },
    { label: 'UAT', count: progressByStatus.uat, color: '#0097A7' },
    { label: 'Test', count: progressByStatus.test, color: '#2563EB' },
    { label: 'In Progress', count: progressByStatus.inProgress, color: '#D97706' },
    { label: 'To Do', count: progressByStatus.todo, color: '#94A3B8' },
  ]

  const burndownRows = currentSprint?.burndown.map((bp) =>
    `<tr><td>${bp.date}</td><td>${bp.baselinePoints}</td><td>${bp.actualPoints}</td><td>${bp.completedPoints}</td></tr>`
  ).join('') ?? ''

  const teamDeliveryRate = developers.length > 0
    ? Math.round(developers.reduce((sum, d) => sum + d.deliveryRate, 0) / developers.length)
    : 0

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <title>${project.name} — Sprint Report</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; color: #1a1a1a; padding: 40px; max-width: 800px; margin: 0 auto; }
    h1 { font-size: 24px; margin-bottom: 4px; }
    h2 { font-size: 16px; margin: 24px 0 12px; color: #374151; }
    .subtitle { font-size: 12px; color: #6b7280; margin-bottom: 24px; }
    .kpi-row { display: flex; gap: 16px; margin-bottom: 24px; }
    .kpi { flex: 1; border: 1px solid #e5e7eb; border-radius: 8px; padding: 16px; }
    .kpi-label { font-size: 11px; color: #6b7280; text-transform: uppercase; letter-spacing: 0.05em; }
    .kpi-value { font-size: 24px; font-weight: 700; margin-top: 4px; }
    table { width: 100%; border-collapse: collapse; font-size: 13px; }
    th, td { padding: 8px 12px; border-bottom: 1px solid #e5e7eb; text-align: left; }
    th { font-size: 11px; text-transform: uppercase; color: #6b7280; font-weight: 600; }
    .status-dot { display: inline-block; width: 8px; height: 8px; border-radius: 50%; margin-right: 6px; }
    .footer { margin-top: 32px; font-size: 11px; color: #9ca3af; border-top: 1px solid #e5e7eb; padding-top: 12px; }
    @media print { body { padding: 20px; } }
  </style>
</head>
<body>
  <h1>${project.name}</h1>
  <p class="subtitle">${project.jiraProjectKey ?? project.azureProjectId ?? ''}${sprint ? ` — ${sprint.name}` : ''} — Generated ${new Date().toLocaleDateString()}</p>

  <div class="kpi-row">
    <div class="kpi">
      <div class="kpi-label">Cards</div>
      <div class="kpi-value">${currentSprint?.totalCards ?? 0}</div>
    </div>
    <div class="kpi">
      <div class="kpi-label">Completed</div>
      <div class="kpi-value">${currentSprint?.completedCards ?? 0}</div>
    </div>
    <div class="kpi">
      <div class="kpi-label">Progress</div>
      <div class="kpi-value">${overview.overallProgress}%</div>
    </div>
    <div class="kpi">
      <div class="kpi-label">Team Delivery</div>
      <div class="kpi-value">${teamDeliveryRate}%</div>
    </div>
  </div>

  <h2>Progress by Status</h2>
  <table>
    <thead><tr><th>Status</th><th>Count</th></tr></thead>
    <tbody>
      ${statusRows.map((s) => `<tr><td><span class="status-dot" style="background:${s.color}"></span>${s.label}</td><td>${s.count}</td></tr>`).join('')}
    </tbody>
  </table>

  ${burndownRows ? `
  <h2>Burndown</h2>
  <table>
    <thead><tr><th>Date</th><th>Baseline</th><th>Actual</th><th>Completed</th></tr></thead>
    <tbody>${burndownRows}</tbody>
  </table>
  ` : ''}

  <h2>Team Delivery Rates</h2>
  <table>
    <thead><tr><th>Developer</th><th>Delivery Rate</th><th>Points</th></tr></thead>
    <tbody>
      ${developers.map((d) => `<tr><td>${d.name}</td><td>${Math.round(d.deliveryRate)}%</td><td>${d.totalPoints}</td></tr>`).join('')}
    </tbody>
  </table>

  <div class="footer">
    Generated by Spravio — ${new Date().toISOString()}
  </div>
</body>
</html>`
}
